################################################################################
# Author's information: 
# Alfredo Sanchez-Tojar (@ASanchez_Tojar)
# Profile: https://goo.gl/PmpPEB
# Meta-research group, University of Coimbra, Portugal
# Email: alfredo.tojar@gmail.com
# Script first created on the 11th of December 2025

###############################################################################
# Description of script and Instructions
################################################################################

# This script imports clean data on bird wing length generated by the script
# 001_data_cleaning.R, and uses that clean dataset to generate a new tree and
# associated phylogenetic correlation matrix. This was done after receiving 
# comments by the reviewers and editor that looked at our manuscript in the 
# journal Evolution. At the end of the script, I export this new matrix and 
# use it in the following scripts. At the end of the script, the updated dataset,
# which contains the new species column is outsourced to be used by script 002

# Study:

# Klaus Reinhold, Alfredo Sánchez-Tójar. 2025. Wing length canalisation and 
# behaviour across birds: a phylogenetic meta-analysis of variance

################################################################################
# Packages needed
################################################################################

# library(devtools)  
# #devtools::install_github("eliotmiller/clootl")

# install.packages("pacman")
pacman::p_load(clootl,readxl,phytools,stringr)

# cleaning environment
rm(list=ls())

################################################################################
# Functions: 
################################################################################

# none needed

################################################################################
# Importing the data 
################################################################################

body.CV.final <- read.csv("data/final/04_final_full_and_clean_bird_wing_size_dataset.csv",
                          header=T,sep=",")


# extractTree() extracts one or more phylogenies in the desired taxonomy and 
# tree version. It defaults to the pre-packaged summary trees, but can also be 
# used to extract sets of phylogenies expressing uncertainty, once they have been 
# downloaded from the online repository.

# in extractTree(), species is a character vector either of scientific names 
# (directly as they come out of the eBird taxonomy, i.e. without underscores) or
# of six-letter eBird species codes. Any elements of the species vector that do 
# not match a species-level taxon in the specified eBird taxonomy will result in 
# an error. eBird taxonomy files can be accessed using taxonomyGet(). Default is 
# set to "all_species".

# getting the taxonomic data to compare and fix any disagreements between our
# data set and that one. Since The eBird taxonomy year the tree should be output 
# in. Current options are 2021-2024. Both numeric and character inputs are 
# acceptable here. Any value aside from these years will result in an error. 
# Default is most recent year., I set it to 2022
taxonomy.file <- taxonomyGet(2024, data_path = FALSE)

# setdiff(dat$Species2,body.CV.final$species.updated)
# setdiff(unique(body.CV.final$species.updated),dat$Species2)
setdiff(unique(body.CV.final$species.updated),taxonomy.file$SCI_NAME)
missing_species <- setdiff(unique(body.CV.final$species.updated),taxonomy.file$SCI_NAME)

# Let's clean this out

# Step 0. Have a copy to modify
body.CV.final$species.updated.new <- NA_character_

# Step 1. Direct match: species.updated == SCI_NAME
# Create a named vector for SCI_NAME
sci_map <- taxonomy.file$SCI_NAME
names(sci_map) <- taxonomy.file$SCI_NAME

# Assign where match is found to ensure species that are already correct keep 
# their name.
body.CV.final$species.updated.new[body.CV.final$species.updated %in% taxonomy.file$SCI_NAME] <- 
  sci_map[body.CV.final$species.updated[body.CV.final$species.updated %in% taxonomy.file$SCI_NAME]]

# Step 2. Second match: species.updated == ott_name --> assign SCI_NAME
# Create a map from ott_name --> SCI_NAME
ott_map <- taxonomy.file$SCI_NAME
names(ott_map) <- taxonomy.file$ott_name

# Find those that didn’t match SCI_NAME
idx_missing <- is.na(body.CV.final$species.updated.new)

# For those, check if their species.updated is in ott_name
to_update <- body.CV.final$species.updated[idx_missing] %in% taxonomy.file$ott_name

# Assign corresponding SCI_NAME if found
body.CV.final$species.updated.new[idx_missing][to_update] <- 
  ott_map[body.CV.final$species.updated[idx_missing][to_update]]

# Step 3. Remaining unmatched = NA
summary(is.na(body.CV.final$species.updated.new))

# Check which are still unmatched
# That gives you the list of species still unresolved (not in SCI_NAME or ott_name).
unmatched <- unique(body.CV.final$species.updated[is.na(body.CV.final$species.updated.new)])
unmatched

# Those two species should correspond to the following, so I am changing them
# manually to

body.CV.final$species.updated.new[body.CV.final$species.updated == "Anas cyanoptera septentrionalium"] <- "Spatula cyanoptera"
body.CV.final$species.updated.new[body.CV.final$species.updated == "Porphyrio porphyrio porphyrio"] <- "Porphyrio porphyrio"


# # searching for the missing species
# taxonomy.file[taxonomy.file$SCI_NAME %in% missing_species, 
#               c("SCI_NAME", "PRIMARY_COM_NAME", "ott_name")] #directly
# 
# 
# # partial / fuzzy matches since some names might differ
# matches <- lapply(missing_species, function(sp) {
#   subset(taxonomy.file, str_detect(SCI_NAME, str_extract(sp, "^[A-Za-z]+\\s[A-Za-z]+")), 
#          select = c("SCI_NAME", "PRIMARY_COM_NAME", "ott_name"))
# })
# # This code:
# # Extracts the first two words (Genus + species epithet),
# # Finds all records in your taxonomy that contain those two words (ignoring subspecies),
# # Returns possible candidate matches.
# 
# names(matches) <- missing_species
# matches
# 
# # extract genus name
# genus_names <- sub(" .*", "", missing_species)
# 
# # search by genus
# matches_by_genus <- lapply(genus_names, function(gen) {
#   subset(taxonomy.file, str_detect(ott_name, paste0("^", gen)))
# })
# names(matches_by_genus) <- missing_species
# 
# # body.CV.final$species.updated to taxonomy.file$SCI_NAME
# # Anas cyanoptera septentrionalium to Spatula cyanoptera
# # Anas discors to Spatula discors
# # Chlidonias hybridus to Chlidonias hybrida
# # Dendrocopos medius to Dendrocoptes medius
# # Picoides pubescens to Dryobates pubescens
# # Diglossopis cyanea to Diglossa cyanea
# # Basileuterus luteoviridis to Myiothlypis luteoviridis
# # Basileuterus signatus to Myiothlypis signata
# # Streptopelia senegalensis to 
# # Abrornis inornata to Phylloscopus inornatus
# # Porphyrio porphyrio porphyrio to Porphyrio porphyrio (not present in ott_name)
# # Sylvia nisoria to Curruca nisoria
# # Thryothorus leucotis to Cantorchilus leucotis


#body.CV.final <- body.CV.final[body.CV.final$species.updated %in% dat$Species2, ]

################################################################################
# GENERATING THE TREE
ex1 <- extractTree(species=body.CV.final$species.updated.new,taxonomy_year = 2024)

#plot(ex1)

################################################################################
# Making the tree and the database agree before we start with anything else
################################################################################

# removing the underscore "_" from the tree tip.label
ex1$tip.label <- gsub("_"," ", ex1$tip.label)

#################################################################################
# Do both species list agree?
# species names in ex1 but not in body.CV.final
setdiff(ex1$tip.label,
        unique(body.CV.final$species.updated.new))

# species names in body.CV.final but not in ex1
setdiff(unique(body.CV.final$species.updated.new),
        ex1$tip.label)


# all correct

################################################################################
# Matrix generation

# check tree is ultrametric
is.ultrametric(ex1) # FALSE
is.binary(ex1)

# the tree is nonultrametric, which needs fixing before a correlation matrix
# is created

# trying to optimise branch rates and node dates 
mytree_ultra <- chronos(ex1) 
is.ultrametric(mytree_ultra) # TRUE

# chronos shows some warnings: stopped before satisfying convergence criteria,
# but the exploration below suggest we probably do not need to worry

# Inspect the tree and the fit
plot(mytree_ultra)
axisPhylo()           # to show time scale when using ape
summary(mytree_ultra) # branch length stats

# matrix to be included in the models
phylo_cor_new <- vcv(mytree_ultra, cor = T)

# Check the VCV for numerical problems
eigs <- eigen(phylo_cor_new, symmetric = TRUE)$values
eigs
min(eigs)  # should be >= 0 (or very small negative rounding)
# All eigenvalues are positive and the smallest is ≈ 0.003. The correlation 
# matrix is positive-definite (or at least not numerically singular), so it 
# should be acceptable to use the matrix. 
# chronos() run produced an ultrametric tree, and the VCV/correlation matrix is 
# numerically well behaved (all eigenvalues > 0, min ≈ 0.003). Technically,
# we can use vcv(..., cor = TRUE)
# phylo_cor_new

# we can now save the tree
save(mytree_ultra, file = "data/phylogeny/tree_McTavish2025.Rdata")

# finally, save matrix for future analyses
save(phylo_cor_new, file = "data/phylogeny/phylo_cor_McTavish2025.Rdata")

# data based used in further scripts after adding species.updated.new
write.csv(body.CV.final,
          "data/final/04B_final_full_and_clean_bird_wing_size_dataset.csv",
          row.names=FALSE)
