################################################################################
# Author's information: 
# Alfredo Sanchez-Tojar (@ASanchez_Tojar)
# Profile: https://goo.gl/PmpPEB
# Department of Evolutionary Biology, Bielefeld University (GER) 
# Email: alfredo.tojar@gmail.com
# Script first created on the 17th of September 2024

################################################################################
# Description of script and Instructions
################################################################################

# This script imports the clean data generated by script 001_data_cleaning.R
# and subsequently updated by the main analyses script 002_data_analysis.R. This
# data correspond to bird wing length CV values across species, which we are 
# trying to understand. The current script focuses on a series of sensitivity
# analyses that we performed to confirm and validate the main analyses performed
# in script 002_data_analysis.R

# For the study:

# Klaus Reinhold, Alfredo Sánchez-Tójar. 2025. Wing length canalisation and 
# behaviour across birds: a phylogenetic meta-analysis of variance

################################################################################
# Packages needed
################################################################################

# install.packages("pacman")
pacman::p_load(ape,metafor,rotl,
               treebase,diagram,dplyr,stringr,ggplot2,wesanderson,
               ggsignif,visdat,cowplot,
               patchwork, # nice resource page https://patchwork.data-imaginist.com/articles/guides/layout.html
               ggstance,ggtree,RColorBrewer,
               tidyverse,ggpubr,orchaRd,clubSandwich)

# cleaning environment
rm(list=ls())


################################################################################
# Functions: 
################################################################################

# function to calculate heterogeneity obtained from:
# https://github.com/Yefeng0920/heterogeneity_ecoevo/tree/main/function

# function to calculate heterogeneity - squared version, including CVH2 and M2
h.calc2 <- function(mod){
  # I2
  # sigma2_v = typical sampling error variance
  sigma2_v <- sum(1 / mod$vi) * (mod$k - 1) /
    (sum(1 / mod$vi)^2 - sum((1 / mod$vi)^2))
  # s^2_t = total variance
  I2_total <- 100 * (sum(mod$sigma2) / (sum(mod$sigma2) + sigma2_v))
  I2_each <- 100 * (mod$sigma2 / (sum(mod$sigma2) + sigma2_v))
  #names(I2_each) <- paste0("I2_", model$s.names)
  #names(I2_total) <- "I2_Total"
  I2s_Shinichi <- c(I2_total, I2_each)
  
  # matrix version  
  W <- solve(mod$V)
  X <- model.matrix(mod)
  P <- W - W %*% X %*% solve(t(X) %*% W %*% X) %*% t(X) %*% W
  I2_total2 <- 100* (sum(mod$sigma2) / (sum(mod$sigma2) + (mod$k - mod$p) / sum(diag(P))))
  I2_each2 <- 100* (mod$sigma2 / (sum(mod$sigma2) + (mod$k - mod$p) / sum(diag(P))))
  #names(I2_each2) <- paste0("I2_", model$s.names)
  #names(I2_total2) <- "I2_Total2"
  I2s_Wolfgang <- c(I2_total2, I2_each2)
  
  
  # CVH2
  CV_total <- (sum(mod$sigma2) / (mod$beta[1])^2)
  CV_each <- (mod$sigma2 / (mod$beta[1])^2)
  
  #names(CVB_each) <- paste0("CVB_", mod$s.names)
  #names(CVB_total) <- "CVB_total"
  CVHs <- c(CV_total, CV_each)
  
  # M2
  M_total <- (sum(mod$sigma2) / (sum(mod$sigma2) + (mod$beta[1])^2))
  M_each <- (mod$sigma2) / (sum(mod$sigma2) + (mod$beta[1])^2)
  Ms <- c(M_total, M_each)
  
  hs <- data.frame(I2s_Shinichi,CVHs,Ms)
  rownames(hs) <- c("Total", mod$s.names)
  return(hs)
}

# function to estimate typical sampling error variance obtained from 
# https://github.com/Yefeng0920/heterogeneity_ecoevo/tree/main/function
sigma2_v <- function(mod){
  sigma2_v <- sum(1 / mod$vi) * (mod$k - 1) /
    (sum(1 / mod$vi)^2 - sum((1 / mod$vi)^2))
  return(sigma2_v)
}


# function for extracting mean and CI from each metafor model
estimates.CI <- function(model){
  db.mf <- data.frame(model$b,row.names = 1:nrow(model$b))
  db.mf <- cbind(db.mf,model$ci.lb,model$ci.ub,row.names(model$b),model$pval)
  names(db.mf) <- c("mean","lower","upper","estimate","p-value")
  return(db.mf[,c("estimate","mean","lower","upper","p-value")])
}

################################################################################
# Importing the data 
################################################################################

# importing final dataset
body.CV.final <- read.csv("data/final/05_final_full_and_clean_bird_wing_size_dataset_with_CV_values.csv",
                          header=T,sep=",")

head(body.CV.final)
summary(body.CV.final)
names(body.CV.final)

################################################################################
# Loading phylogenetic information

# taxonomic information: taxa
load("data/phylogeny/taxa_Open_Tree_of_Life_20240909.RData")

# tree: tree_random
load("data/phylogeny/tree_random_20240909.Rdata")

# phylogenetic matrix: phylo_cor
load("data/phylogeny/phylo_cor_20240909.Rdata")



################################################################################
# S5. Sensitivity analyses: Treating vagrants as migrants
################################################################################

################################################################################
# Final dataset preparation before analyses
################################################################################

# converting some variables types to factors
cols.factors <- c("population_ID","species.updated","species",
                  "study_ID","reference_link","subset",
                  "trait","unit","measurement_notes",
                  "pair_ID","sex","migratory","feeding.type",
                  "migratory.pop.level","feeding.type.pop.level",
                  "migratory.inc.vagrants.pop.level","migratory.inc.vagrants",
                  "species.updated.rep")

body.CV.final[cols.factors] <- lapply(body.CV.final[cols.factors], 
                                      factor)

summary(body.CV.final)

# setting reference levels and order for the factorial moderators
body.CV.final$feeding.type <- factor(body.CV.final$feeding.type, 
                                     levels=c("non-aerial feeding",
                                              "partially aerial feeding",
                                              "fully aerial feeding"))

body.CV.final$feeding.type.pop.level <- factor(body.CV.final$feeding.type.pop.level, 
                                               levels=c("non-aerial feeding",
                                                        "fully aerial feeding"))

body.CV.final$migratory.inc.vagrants <- factor(body.CV.final$migratory.inc.vagrants, 
                                               levels=c("non-migratory",
                                                        "partially migratory",
                                                        "fully migratory"))

body.CV.final$migratory.inc.vagrants.pop.level <- factor(body.CV.final$migratory.inc.vagrants.pop.level, 
                                               levels=c("non-migratory",
                                                        "fully migratory"))

summary(body.CV.final)


################################################################################
# Variance-Covariance Matrix
################################################################################

VCV.0.50.study_ID <- impute_covariance_matrix(vi = body.CV.final$vi, 
                                              cluster = body.CV.final$study_ID, 
                                              r = 0.50)

################################################################################
# Meta-regressions
################################################################################

################################################################################
# MIGRATORY: species-specific INCLUDING VAGRANTS
################################################################################

# metaregression_unimoderator_migratory_inc_vagrants <- rma.mv(yi = yi,
#                                                              V = VCV.0.50.study_ID,
#                                                              mod = ~ 1 +
#                                                                migratory.inc.vagrants,
#                                                              random = list(~ 1 | species.updated.rep,
#                                                                            ~ 1 | species.updated,
#                                                                            ~ 1 | study_ID,
#                                                                            ~ 1 | population_ID,
#                                                                            ~ 1 | pair_ID,
#                                                                            ~ 1 | effectsize_ID),
#                                                              R = list(species.updated = phylo_cor),
#                                                              data=body.CV.final,
#                                                              method="REML",
#                                                              test="t")
# 
# save(metaregression_unimoderator_migratory_inc_vagrants,
#      file="models/sensitivity_analyses/metaregression_unimoderator_migratory_inc_vagrants.RData")
load("models/sensitivity_analyses/metaregression_unimoderator_migratory_inc_vagrants.RData")


summary(metaregression_unimoderator_migratory_inc_vagrants,3)

# getting marginal R2
round(r2_ml(metaregression_unimoderator_migratory_inc_vagrants)*100,2)


# the equivalent model but without intercept 
# metaregression_unimoderator_migratory_inc_vagrants.nointercept <- rma.mv(yi = yi,
#                                                                          V = VCV.0.50.study_ID,
#                                                                          mod = ~ -1 +
#                                                                            migratory.inc.vagrants,
#                                                                          random = list(~ 1 | species.updated.rep,
#                                                                                        ~ 1 | species.updated,
#                                                                                        ~ 1 | study_ID,
#                                                                                        ~ 1 | population_ID,
#                                                                                        ~ 1 | pair_ID,
#                                                                                        ~ 1 | effectsize_ID),
#                                                                          R = list(species.updated = phylo_cor),
#                                                                          data=body.CV.final,
#                                                                          method="REML",
#                                                                          test="t")
# 
# save(metaregression_unimoderator_migratory_inc_vagrants.nointercept,
#      file="models/sensitivity_analyses/metaregression_unimoderator_migratory_inc_vagrants_nointercept.RData")
load("models/sensitivity_analyses/metaregression_unimoderator_migratory_inc_vagrants_nointercept.RData")

# getting marginal R2
round(r2_ml(metaregression_unimoderator_migratory_inc_vagrants.nointercept)*100,2)

summary(metaregression_unimoderator_migratory_inc_vagrants.nointercept,3)
round(exp(metaregression_unimoderator_migratory_inc_vagrants.nointercept$beta)*100,2)
round(exp(metaregression_unimoderator_migratory_inc_vagrants.nointercept$ci.lb)*100,2)
round(exp(metaregression_unimoderator_migratory_inc_vagrants.nointercept$ci.ub)*100,2)


################################################################################
# plotting results

orchard.plot.migratory.inc.vagrants <- orchaRd::orchard_plot(metaregression_unimoderator_migratory_inc_vagrants, 
                                                             mod = "migratory.inc.vagrants", 
                                                             group = "species.updated.rep", 
                                                             xlab = "Effect size (CV %)",
                                                             trunk.size = 1.55,
                                                             branch.size = 3.5,
                                                             twig.size = 1.25,
                                                             transfm  = "percent",
                                                             colour = F)
orchard.plot.migratory.inc.vagrants + 
  scale_y_continuous(limits = c(0,15),
                     breaks = seq(0,15,1))


################################################################################
# FEEDING AND MIGRATORY: species-specific INCLUDING VAGRANTS
################################################################################

# metaregression_feeding_and_migratory_inc_vagrants <- rma.mv(yi = yi,
#                                                             V = VCV.0.50.study_ID,
#                                                             mod = ~ 1 +
#                                                               migratory.inc.vagrants +
#                                                               feeding.type,
#                                                             random = list(~ 1 | species.updated.rep,
#                                                                           ~ 1 | species.updated,
#                                                                           ~ 1 | study_ID,
#                                                                           ~ 1 | population_ID,
#                                                                           ~ 1 | pair_ID,
#                                                                           ~ 1 | effectsize_ID),
#                                                             R = list(species.updated = phylo_cor),
#                                                             data=body.CV.final,
#                                                             method="REML",
#                                                             test="t")
# 
# save(metaregression_feeding_and_migratory_inc_vagrants,
#      file="models/sensitivity_analyses/metaregression_feeding_and_migratory_inc_vagrants.RData")
load("models/sensitivity_analyses/metaregression_feeding_and_migratory_inc_vagrants.RData")


summary(metaregression_feeding_and_migratory_inc_vagrants,3)
round(r2_ml(metaregression_feeding_and_migratory_inc_vagrants)*100,2)



################################################################################
# MIGRATORY: population-specific INCLUDING VAGRANTS
################################################################################

# metaregression_unimoderator_migratory_inc_vagrants_pop_level <- rma.mv(yi = yi,
#                                                                        V = VCV.0.50.study_ID,
#                                                                        mod = ~ 1 +
#                                                                          migratory.inc.vagrants.pop.level,
#                                                                        random = list(~ 1 | species.updated.rep,
#                                                                                      ~ 1 | species.updated,
#                                                                                      ~ 1 | study_ID,
#                                                                                      ~ 1 | population_ID,
#                                                                                      ~ 1 | pair_ID,
#                                                                                      ~ 1 | effectsize_ID),
#                                                                        R = list(species.updated = phylo_cor),
#                                                                        data=body.CV.final,
#                                                                        method="REML",
#                                                                        test="t")
# 
# save(metaregression_unimoderator_migratory_inc_vagrants_pop_level,
#      file="models/sensitivity_analyses/metaregression_unimoderator_migratory_inc_vagrants_pop_level.RData")
load("models/sensitivity_analyses/metaregression_unimoderator_migratory_inc_vagrants_pop_level.RData")


summary(metaregression_unimoderator_migratory_inc_vagrants_pop_level,3)

# getting marginal R2
round(r2_ml(metaregression_unimoderator_migratory_inc_vagrants_pop_level)*100,2)


# the equivalent model but without intercept 
# metaregression_unimoderator_migratory_inc_vagrants_pop_level.nointercept <- rma.mv(yi = yi,
#                                                                                    V = VCV.0.50.study_ID,
#                                                                                    mod = ~ -1 +
#                                                                                      migratory.inc.vagrants.pop.level,
#                                                                                    random = list(~ 1 | species.updated.rep,
#                                                                                                  ~ 1 | species.updated,
#                                                                                                  ~ 1 | study_ID,
#                                                                                                  ~ 1 | population_ID,
#                                                                                                  ~ 1 | pair_ID,
#                                                                                                  ~ 1 | effectsize_ID),
#                                                                                    R = list(species.updated = phylo_cor),
#                                                                                    data=body.CV.final,
#                                                                                    method="REML",
#                                                                                    test="t")
# 
# save(metaregression_unimoderator_migratory_inc_vagrants_pop_level.nointercept,
#      file="models/sensitivity_analyses/metaregression_unimoderator_migratory_inc_vagrants_pop_level_nointercept.RData")
load("models/sensitivity_analyses/metaregression_unimoderator_migratory_inc_vagrants_pop_level_nointercept.RData")

# getting marginal R2
round(r2_ml(metaregression_unimoderator_migratory_inc_vagrants_pop_level.nointercept)*100,2)

summary(metaregression_unimoderator_migratory_inc_vagrants_pop_level.nointercept,3)
round(exp(metaregression_unimoderator_migratory_inc_vagrants_pop_level.nointercept$beta)*100,2)
round(exp(metaregression_unimoderator_migratory_inc_vagrants_pop_level.nointercept$ci.lb)*100,2)
round(exp(metaregression_unimoderator_migratory_inc_vagrants_pop_level.nointercept$ci.ub)*100,2)


################################################################################
# plotting results

orchard.plot.migratory.pop.level.inc.vagrants <- orchaRd::orchard_plot(metaregression_unimoderator_migratory_inc_vagrants_pop_level, 
                                                                       mod = "migratory.inc.vagrants.pop.level", 
                                                                       group = "species.updated.rep", 
                                                                       xlab = "Effect size (CV %)",
                                                                       trunk.size = 1.55,
                                                                       branch.size = 3.5,
                                                                       twig.size = 1.25,
                                                                       transfm  = "percent",
                                                                       colour = F)
orchard.plot.migratory.pop.level.inc.vagrants + 
  scale_y_continuous(limits = c(0,15),
                     breaks = seq(0,15,1))



################################################################################
# FEEDING AND MIGRATORY: population-specific INCLUDING VAGRANTS
################################################################################

# metaregression_feeding_and_migratory_inc_vagrants_pop_level <- rma.mv(yi = yi,
#                                                                       V = VCV.0.50.study_ID,
#                                                                       mod = ~ 1 +
#                                                                         migratory.inc.vagrants.pop.level +
#                                                                         feeding.type.pop.level,
#                                                                       random = list(~ 1 | species.updated.rep,
#                                                                                     ~ 1 | species.updated,
#                                                                                     ~ 1 | study_ID,
#                                                                                     ~ 1 | population_ID,
#                                                                                     ~ 1 | pair_ID,
#                                                                                     ~ 1 | effectsize_ID),
#                                                                       R = list(species.updated = phylo_cor),
#                                                                       data=body.CV.final,
#                                                                       method="REML",
#                                                                       test="t")
# 
# save(metaregression_feeding_and_migratory_inc_vagrants_pop_level,
#      file="models/sensitivity_analyses/metaregression_feeding_and_migratory_inc_vagrants_pop_level.RData")
load("models/sensitivity_analyses/metaregression_feeding_and_migratory_inc_vagrants_pop_level.RData")


summary(metaregression_feeding_and_migratory_inc_vagrants_pop_level,3)

# getting marginal R2
round(r2_ml(metaregression_feeding_and_migratory_inc_vagrants_pop_level)*100,2)
